version: '3.3'
services:
    db:
        container_name: db
        image: mysql:8
        environment:
            MYSQL_DATABASE: studentdb
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: supersecret
        ports:
        - 3306:3306
    web:
        image: retail-store-api:1.6
        ports:
        - 8080:8080
        - 9990:9990
        depends_on:
        - db